/**
 * Created by tmh on 16/7/29.
 */
var GameConstants = {
    GAME_STATE_IDLE:0,
    GAME_STATE_FLYING:1,
    GAME_STATE_OVER:2,
    HERO_STATE_IDIE:0,
    HERO_STATE_FLYING:1,
    HERO_STATE_HIT:2,
    HERO_STATE_FALL:3,
    HERO_LIVES:5,
    HERO_DISTANCE:0,
    HERO_SCORE:0,
    HERO_MIN_SPEED:5,
    GIRL_SCALE:0.15
};